glpsol -m coloring.mod -d 2-FullIns_3.dat   -o .\output\2-FullIns_3.out  --tmlim 1200 > .\output-bash\2-FullIns_3.txt
glpsol -m coloring.mod -d queen5_5.dat      -o .\output\queen5_5.out     --tmlim 1200 > .\output-bash\queen5_5.txt
glpsol -m coloring.mod -d queen6_6.dat      -o .\output\queen6_6.out     --tmlim 1200 > .\output-bash\queen6_6.txt
glpsol -m coloring.mod -d queen7_7.dat      -o .\output\queen7_7.out     --tmlim 1200 > .\output-bash\queen7_7.txt
glpsol -m coloring.mod -d queen9_9.dat      -o .\output\queen9_9.out     --tmlim 1200 > .\output-bash\queen9_9.txt
glpsol -m coloring.mod -d queen11_11.dat    -o .\output\queen11_11.out   --tmlim 1200 > .\output-bash\queen11_11.txt
glpsol -m coloring.mod -d 4-FullIns_3.dat   -o .\output\4-FullIns_3.out  --tmlim 1200 > .\output-bash\4-FullIns_3.txt
glpsol -m coloring.mod -d 5-FullIns_3.dat   -o .\output\5-FullIns_3.out  --tmlim 1200 > .\output-bash\5-FullIns_3.txt
glpsol -m coloring.mod -d queen10_10.dat    -o .\output\queen10_10.out   --tmlim 1200 > .\output-bash\queen10_10.txt
glpsol -m coloring.mod -d 2-FullIns_4.dat   -o .\output\2-FullIns_4.out  --tmlim 1200 > .\output-bash\2-FullIns_4.txt